name: CI/CD Pipeline

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Integration Tests
      run: mvn test

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: developeriq.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image to ACR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: developeriq.azurecr.io/github-metrics-service:${{ github.sha }}

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Set up Kubernetes config
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Update Deployment Image Tag
      run: |
        sed -i 's/IMAGE_TAG/${{ github.sha }}/g' deployment.yml

    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yml

    - name: Deploy Ingress Controller
      run: kubectl apply -f ingress-controller.yml